--- # Install MariaDB
- hosts: localhost
  remote_user: root
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  tasks:
    - name: Installing MariaDB
      yum: 
        name: mariadb-server
        state: latest
      notify: 
        - startservice
  handlers: 
    - name: startservice
      service: 
        name: mariadb
        state: restarted
